field: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
fieldLayouts:
  73281f26-73de-4318-a067-3d6c6905b1cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7bf7da79-8f7d-4a1b-8129-121b24c0d99b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98f0e07e-81da-484f-8190-987af0f739c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21077893-9405-4330-ba61-9f695515c9fb # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 360e355c-d9f2-417d-af9f-ce89b15c6e4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da3d7ec4-1d85-47ba-a517-6c81d94cc9d2 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b95dfd47-bd17-4d2d-b2f5-586a0750667f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f2e4fad-7ce3-4757-abbd-6483c2dc8abe
        userCondition: null
fields:
  7bf7da79-8f7d-4a1b-8129-121b24c0d99b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: true
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      restrictedLocationSubpath: hero
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  21077893-9405-4330-ba61-9f695515c9fb: # Hero Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heroTitle
    instructions: 'If empty page title will be used'
    name: 'Hero Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  da3d7ec4-1d85-47ba-a517-6c81d94cc9d2: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 3e09420e-30db-49dd-9520-4775f6667303 # Site Basic
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
handle: standardHero
name: 'Standard Hero'
sortOrder: 1
