fieldLayouts:
  eb53ac7e-fc3b-4522-a428-91addf2ec44f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 541ec78b-792f-4edb-a994-06a8971aa7b5
            warning: null
            width: 100
        name: Content
        uid: b560c7ff-4231-406d-975b-a98c765ba8df
fs: userGuide
handle: userGuide
name: 'User Guide'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
