columnSuffix: null
contentColumnType: string
fieldGroup: d1511275-c802-4850-9b74-6e305f2cc1c7 # Asset Fields
handle: newsCategories
instructions: null
name: 'News Categories'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: true
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:4b342e70-0223-4c29-9237-86a023f74f1b' # News Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
