columnSuffix: null
contentColumnType: string
fieldGroup: ca4cf186-4f48-488c-adbc-d38eba9d2533 # User Guide
handle: userGuide
instructions: null
name: 'User Guide'
searchable: false
settings:
  contentTable: '{{%matrixcontent_userguide}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
